### ISSUE TITLE
jnbt.mc is missing __init__ file and is not installed with setup.py

### ISSUE THREAD

**Issue by Martmists-GH** [theJ8910/jnbt#2]

**Comment by theJ8910** [comment]
Oh man, how long has that been broken. 😅
Thanks for the report. I did a quick test install on another computer and confirmed the issue.

I've added an \_\_init\_\_.py to jnbt.mc (and made setup.py actually include it in the distribution package), so this should be fixed now. If for some reason it isn't though, feel free to reopen the issue.
